name = "birol-site"
compatibility_date = "2025-01-08"
main = "./dist/_worker.js/index.js"
secrets_store_secrets = [
  { binding = "ADMIN_PASSWORD", store_id = "4370508a5185475d83f789521a8ad712", secret_name = "ADMIN_PASSWORD" }
]
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

[[r2_buckets]]
binding = "GALLERY_BUCKET"
bucket_name = "gallery-images"

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "birol-site"

